# Generated by Django 5.2.4 on 2025-07-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SC_NO', models.CharField(blank=True, max_length=20, null=True)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('DOB', models.DateField()),
                ('ContactNo', models.CharField(max_length=20)),
                ('CitizenshipNo', models.CharField(max_length=50, unique=True)),
                ('LocationCitizenship', models.CharField(max_length=100)),
                ('PropertyFileLocation', models.CharField(max_length=255)),
                ('BranchID', models.IntegerField()),
                ('DemandTypeID', models.IntegerField()),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
