# Generated by Django 5.2.4 on 2025-07-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Logo', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
    ]
