# Generated by Django 5.2.4 on 2025-07-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='BranchID',
            new_name='branch_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CitizenshipNo',
            new_name='citizenship_no',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ContactNo',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='DemandTypeID',
            new_name='demand_type_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='LocationCitizenship',
            new_name='location_citizenship',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='PropertyFileLocation',
            new_name='property_file_location',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='SC_NO',
            new_name='sc_no',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='Logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='Name',
            new_name='name',
        ),
    ]
