# Generated by Django 5.2.4 on 2025-07-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('rate_per_unit', models.FloatField()),
                ('minimum_charge', models.FloatField()),
            ],
            options={
                'db_table': 'demand_types',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'employee_types',
            },
        ),
    ]
