# Generated by Django 5.2.4 on 2025-07-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_user_profile_picture_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_type',
        ),
        migrations.DeleteModel(
            name='EmployeeType',
        ),
    ]
