# Generated by Django 5.2.4 on 2025-07-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
