# Generated by Django 5.2.4 on 2025-07-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_remove_customer_user_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepaliMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveSmallIntegerField(help_text='Month number 1-12', unique=True)),
                ('name_en', models.CharField(help_text='English month name', max_length=50, unique=True)),
                ('name_np', models.CharField(help_text='Nepali month name (in Nepali script)', max_length=50, unique=True)),
                ('abbreviation', models.CharField(blank=True, help_text='Optional short form', max_length=10, null=True)),
            ],
            options={
                'db_table': 'nepali_months',
                'ordering': ['month_number'],
            },
        ),
    ]
